### ISSUE TITLE
Missing a header file

### ISSUE THREAD

**Issue by ghost** [nanu2000/Light-Show-Engine#1]
ModelLoader.h is missing from the repository.

**Comment by richies-dev** [comment]
The ModelLoader .cpp/.h files are not needed for the engine to run. They were used to create .3DMA/.3DM files from .obj/.dae/.fbx files, but were later moved to another project so that this project does not have to rely on Assimp to read files.

I forgot to remove the ModelLoader.cpp file from the LightShowEngine file directory when I added everything to GitHub.
